#DATA
img_dir: data/Tree_RGB
mask_dir: data/Tree_masks
mean: [0.485, 0.456, 0.406]
std: 0.229, 0.224, 0.225]
max_pixel_value: 255.0

#MODEL
batch_size: 2
learning_rate: 1e-3
weight_decay: 1e-4
num_epochs: 5
img_size: (256,256)