#DATA
data_dir: ../../../data_samples/drive_data/patches
input_folders: ["DSM", "RGB"]
input_channels: 4
output_folder: "masks"
mean: [0.485]
std: [0.229]
max_pixel_value: 255.0

#MODEL
batch_size: 1
learning_rate: 0.001
weight_decay: 0.0001
num_epochs: 5
img_size: [256,256]

#OUTPUT
save_output_path: run_output