#DATA
data_dir: ../../../data_samples/drive_data/patches
input_folders: ["RGB", "DSM"]
input_channels: 4
output_folder: "masks"

#MODEL
use_pretrained: False
batch_size: 1
learning_rate: 0.001
weight_decay: 0.0001
num_epochs: 1
img_size: [256,256]
features: [64, 128, 256, 512]

#OUTPUT
save_output_path: run_output
save_predictions: False
save_model: True

#REPORTING
log_in_wandb: True